# Generated by Django 3.1.8 on 2021-05-16 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210516_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='AccountTransactions',
        ),
    ]
