# Generated by Django 3.1.8 on 2022-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210516_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='mobile_number',
            field=models.CharField(default=92123456789, max_length=24),
            preserve_default=False,
        ),
    ]
